config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :reviews, except: [:show, :index]
  end
  resources :cart_items
  resources :carts, :path => "/cart"
  resources :cart
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'user/index'
  get '/news', to: 'news#index'
  get '/basics', to: 'basics#quotations'
  get '/admin' , to: 'basics#admin'
  get '/planning', to: 'basics#index'
  match '/basics', :to => "basics#quotations", :via => [:get, :post]
  resources :basics
  resources :orders
  resources :quotations
  resources :wait_queue
  resources :restaurants do
    resources :restaurant_tables
    resources :menus
    resources :users, :path => "/staff"
  end
  # post '/restaurants/:restaurant_id/restaurant_tables/:id' 
  resources :profile
  post '/restaurants/:id' => 'restaurants#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/solutions', to: 'site#solutions'
  get '/browse', to: 'restaurants#browse'
  root to: 'site#index'

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    belongs_to :user
    has_many :reviews
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
    validates_presence_of :category, :quote, :author_name
    # attr_accessor :new_category
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :restaurant_table, dependent: :destroy
  has_many :wait_queue, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :users, through: :staffs
  
  accepts_nested_attributes_for :user

  has_one_attached :qr_code

  def self.search_name(search)
    with_attached_qr_code.
      references(:attachment_attachment).
      where(ActiveStorage::Blob.arel_table[:filename].matches("%#{search}%"))
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    
  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :phone_number
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }
  # validates :phone_number, format: { with: /\A\d{10}\z|\A\d{4}-{1}\d{6}\z/ , message: "bad format" }
  has_many :staffs
  has_one :cart
  has_many :restaurants
  has_many :wait_queues
  has_many :restaurant_tables
  has_many :restaurants, through: :staffs
  accepts_nested_attributes_for :restaurants
  has_many :orders
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # validates :rating, numericality: { in: 0..5 }

  def active_for_authentication?
    super && special_condition_is_valid?
  end

  def active_for_authentication?
    super && !self.banned
  end

end

app/models/wait_queue.rb
class WaitQueue < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  enum status: [:canceled, :waiting, :pending, :completed]
  
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base

  before_action :set_cart

  def index
    @cart_contents = @cart.cart_items.all
  end

  private

    def cart_params
      params.require(:cart).permit(:total, :user_id)
    end

end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Your Cart</h1>

  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Amount</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @cart_contents.each do |cart| %>
        <tr>
          <td><%= image_tag(cart.menu.photo_url, width: 50) %><%= cart.menu.name %></td>
          <td><%= cart.quantity %></td>
          <td><%= cart.quantity * cart.menu.price %></td>
          <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
          <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>Total: </td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%= button_to "ORDER", orders_path%></td>
        </tr>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Cart', new_cart_path %>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @cart.total %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>