config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :reviews, except: [:show, :index]
  end
  resources :cart_items
  resources :carts, :path => "/cart"
  resources :cart
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'user/index'
  get '/news', to: 'news#index'
  get '/basics', to: 'basics#quotations'
  get '/admin' , to: 'basics#admin'
  get '/planning', to: 'basics#index'
  match '/basics', :to => "basics#quotations", :via => [:get, :post]
  resources :basics
  resources :orders
  resources :quotations
  resources :wait_queue
  resources :restaurants do
    resources :restaurant_tables
    resources :menus
    resources :users, :path => "/staff"
  end
  # post '/restaurants/:restaurant_id/restaurant_tables/:id' 
  resources :profile
  post '/restaurants/:id' => 'restaurants#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/solutions', to: 'site#solutions'
  get '/browse', to: 'restaurants#browse'
  root to: 'site#index'

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    belongs_to :user
    has_many :reviews
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
    validates_presence_of :category, :quote, :author_name
    # attr_accessor :new_category
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :restaurant_table, dependent: :destroy
  has_many :wait_queue, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :users, through: :staffs
  
  accepts_nested_attributes_for :user

  has_one_attached :qr_code

  def self.search_name(search)
    with_attached_qr_code.
      references(:attachment_attachment).
      where(ActiveStorage::Blob.arel_table[:filename].matches("%#{search}%"))
  end
  
end

app/models/restaurant_table.rb
class RestaurantTable < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :restaurant
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    
  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :phone_number
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }
  # validates :phone_number, format: { with: /\A\d{10}\z|\A\d{4}-{1}\d{6}\z/ , message: "bad format" }
  has_many :staffs
  has_one :cart
  has_many :restaurants
  has_many :wait_queues
  has_many :restaurant_tables
  has_many :restaurants, through: :staffs
  accepts_nested_attributes_for :restaurants
  has_many :orders
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # validates :rating, numericality: { in: 0..5 }

  def active_for_authentication?
    super && special_condition_is_valid?
  end

  def active_for_authentication?
    super && !self.banned
  end

end

app/models/wait_queue.rb
class WaitQueue < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  enum status: [:canceled, :waiting, :pending, :completed]
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :get_user
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :set_title

  def browse
    @restaurants = Restaurant.all
    puts @restaurants.inspect
    respond_to do |format|
      format.html
      format.json { render json: @restaurants }
      format.xml { render xml: @restaurants }
      end
  end

  def index
    @restaurants = Restaurant.where(user_id: @current_user)
    respond_to do |format|
      format.html
      format.json { render json: @restaurants }
      format.xml { render xml: @restaurants }
      end
  end

  def show 
    if params[:search_name]
      @employees = User.where(email: params[:search_name])
    end

    if params[:add_new_employee]
      @employee = User.find_by_email(params[:add_new_employee])
      @new_staff = Staff.new({:user_id => @employee.id, :restaurant_id => @restaurant.id})
      respond_to do |format|
        if @new_staff.save
          format.html { redirect_to restaurant_url(@restaurant), notice: "Staff was successfully added." }
          format.json { render :show, status: :created, location: @restaurant }
        else
          format.html { render :show, status: :unprocessable_entity }
          format.json { render json: @restaurant.errors, status: :unprocessable_entity }
        end
      end
    end

    if params[:remove_employee]
      user = User.find_by_email(params[:remove_employee])
      @restaurant.staffs.find_by_user_id(user).delete
    end



    @menus = Menu.where(restaurant_id: params[:id])
    @staff_list = @restaurant.users
    @queues = @restaurant.wait_queue
  end

  # GET /projects/new
  def new
    @restaurant = current_user.restaurants.new
  end

  def create
    @restaurant = current_user.restaurants.create(restaurant_params)
    @restaurant.user_id = current_user.id
    @restaurant.queuetime = default_wait_queue_time
    respond_to do |format|
      if @restaurant.save
        #  CREATE QR CODE HERE
        create_qr_code(@restaurant)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      qr_id = @restaurant.qr_code_blob.filename
      if File.exists?("tmp/#{qr_id}.png")
        File.delete("tmp/#{qr_id}.png")
      end
    super()
  end

  def create_qr_code(restaurant)
    GenerateQr.new(restaurant, request.host).call()
  end

  private
  
  def get_user
    @currentUser = current_user.id
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :user_id, :queuetime, :photo_url)
  end

  def set_title
    @title = 'My Restaurants'
    @subtitle = 'Manage my restaurants!'
  end

end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

<% if !form.object.new_record? %>
  <div class="field">
    <%= form.label :photo_url, 'Add Photo' %> 
    <%= form.text_area :photo_url %> 
  </div>

   <div class="field">
    <%= form.label :queuetime, 'Queue time (*in minutes)' %> 
    <%= form.number_field :queuetime %> 
  </div>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/browse.html.erb
<div class="container">

    <div class="block">
        <h2>Restaurants</h2>
    </div>
    <div class="columns">
        <% @restaurants.each do |s| %>
        <div class="column is-one-quarter">
            <div class="card">
                <div class="card-image">
                    <figure class="image is-4by3">
                    <%= image_tag(s.photo_url ) if s.photo_url? %>
                    </figure>
                </div>
                <div class="card-content">
                    <p class="title is-4"><%= s.name %></p>
                    <div class="content card-image has-text-centered">
                        <figure class="image is-256x256 is-inline-block">
                        <%= image_tag(s.qr_code ) if s.qr_code.attached? %>
                        </figure>
                    </div>
                </div>
            </div>
        </div>
        <%end%>
    </div>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Restaurants</h1>

<table class='table'>
  <thead>
    <tr>
      <th>id</th>
      <th>Photo</th>
      <th>Name</th>
      <th>Address</th>
      <th>Qr Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td width="200">
         <% if restaurant.qr_code %>
        <%= image_tag(restaurant.qr_code) if restaurant.qr_code.attached? %>
        <%else%>
        No image
        <% end %>
        </td>
        <td>
        <% if restaurant.photo_url %>
        <%= link_to image_tag(restaurant.photo_url, size: "250"), restaurant %>
        <%else%>
        No image
        <% end %>
        </td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">

<div class="columns">

<div class="column is-two-thirds">
    <%= image_tag(@restaurant.photo_url,size: "250")  if @restaurant.photo_url? %>
    <p id="notice"><%= notice %></p>
    <h2>Restaurant Details</h2>
    <%= image_tag(@restaurant.qr_code,size: "250")  if @restaurant.qr_code.attached? %>
    <p>
      <strong>Name:</strong>
      <%= @restaurant.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Default queue time:</strong>
      <%= @restaurant.queuetime %> mins
    </p>


    <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
    <%= link_to 'Back', restaurants_path %>
    <br/>
    <%= link_to 'Manage tables', restaurant_restaurant_tables_path(@restaurant) %>

<hr>
<h2>Staff</h2>
<table class="table table-striped">
<thead>
  <tr>
    <th>Username</th>
    <th>first_name</th>
    <th>Last_name</th>
    <th>phone_number</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @staff_list.each do |staff| %>
  <tr>
    <td><%= staff.username %></td>
    <td><%= staff.first_name %></td>
    <td><%= staff.last_name %></td>
    <td><%= staff.phone_number %></td>
    <td><%= button_to 'Remove', {:action => :show, :remove_employee => staff.email} %></td>
  </tr>
  <%end%>
</tbody>
</table>
<%= form_with :url => { :action => :show } do |form| %>
<div class="field is-grouped">
 <div class="control is-expanded">
  <%= form.label :search_name, "Add employeees"%>
  <%= form.text_field :search_name, :placeholder => 'e.g st122004@ait.asia ', :class => 'input' %>
  </div>
  <div class="control">
  <%= form.submit 'Search', :class => "button is-info" %>
  </div>
</div>
<% end %>
<% if defined?(@employees) %>
<div class="columns">
  <div class="column">
  <% if @employees.length() == 0 %>
    Can't find user with that email.
  <%else%>
    <table class="table table-striped">
      <tr>
        <th>Email</th>
        <th>First name</th>
        <th></th>
      </tr>
      <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.email %></td>
        <td><%= employee.first_name %></td>
        <td><%= button_to 'Add', {:action => :show, :add_new_employee => employee.email} %></td>
      </tr>
      <% end %>
    </table>
    <%end%>
  </div>
</div>
<% end %>

<hr>
<h2>Menus</h2>
<table class="table table-striped">
<thead>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Photo_URL</th>
    <th colspan=2></th>
  </tr>
</thead>
<tbody>
  <% for menu in @menus%>
  <tr>
    <td><%= menu.name %></td>
    <td><%= menu.price %></td>
    <td><img src=<%= menu.photo_url %> width="100px" /></td>
    <td><%= link_to 'Edit', edit_restaurant_menu_path(@restaurant, menu) %></td>
    <td><%= link_to "Delete", restaurant_menu_url(@restaurant, menu), method: :delete %></td>
  </tr>
  <%end%>
</tbody>
</table> 
<%= link_to 'Add new menu', new_restaurant_menu_path(@restaurant) %>
</div>

<div class="column is-one-third">
  <h2>Queues</h2>
  <table class="table table-striped">
<thead>
  <tr>
    <th>Userid</th>
    <th>Status</th>
    <th>Started</th>
    <th>End in</th>
  </tr>
</thead>
<tbody>
  <% @queues.each do |q|%>
  <tr>
    <td><%= q.user_id %></td>
    <td><%= q.status %></td>
    <td><%= q.created_at %></td>
    <td><%= q.end_date %></td>
  </tr>
  <%end%>
</tbody>
</table>
</div>

</div> <%# Columns %>

</div> <%# Container %>