config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :reviews, except: [:show, :index]
  end
  resources :cart_items
  resources :carts, :path => "/cart"
  resources :cart
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'user/index'
  get '/news', to: 'news#index'
  get '/basics', to: 'basics#quotations'
  get '/admin' , to: 'basics#admin'
  get '/planning', to: 'basics#index'
  match '/basics', :to => "basics#quotations", :via => [:get, :post]
  resources :basics
  resources :orders
  resources :quotations
  resources :wait_queue
  resources :restaurants do
    resources :restaurant_tables
    resources :menus
    resources :users, :path => "/staff"
  end
  # post '/restaurants/:restaurant_id/restaurant_tables/:id' 
  resources :profile
  post '/restaurants/:id' => 'restaurants#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/solutions', to: 'site#solutions'
  get '/browse', to: 'restaurants#browse'
  root to: 'site#index'

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    belongs_to :user
    has_many :reviews
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
    validates_presence_of :category, :quote, :author_name
    # attr_accessor :new_category
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_many :restaurant_table, dependent: :destroy
  has_many :wait_queue, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :users, through: :staffs
  
  accepts_nested_attributes_for :user

  has_one_attached :qr_code

  def self.search_name(search)
    with_attached_qr_code.
      references(:attachment_attachment).
      where(ActiveStorage::Blob.arel_table[:filename].matches("%#{search}%"))
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
    MAX_RATING = 5
    validates :rating, numericality: { in: 0..MAX_RATING }
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    
  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :phone_number
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }
  # validates :phone_number, format: { with: /\A\d{10}\z|\A\d{4}-{1}\d{6}\z/ , message: "bad format" }
  has_many :staffs
  has_one :cart
  has_many :restaurants
  has_many :wait_queues
  has_many :restaurant_tables
  has_many :restaurants, through: :staffs
  accepts_nested_attributes_for :restaurants
  has_many :orders
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # validates :rating, numericality: { in: 0..5 }

  def active_for_authentication?
    super && special_condition_is_valid?
  end

  def active_for_authentication?
    super && !self.banned
  end

end

app/models/wait_queue.rb
class WaitQueue < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  enum status: [:canceled, :waiting, :pending, :completed]
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
    @reviews = Review.where(hotel_id: @hotel.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /hotels/new
  def new
    @hotel = current_user.hotels.build
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = current_user.hotels.build(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :description, :address, :owner, :rating)
    end
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: @hotel) do |form| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.select :rating, [["1 Star Restaurant",1], ["2 Star Restaurant", 2], ["3 Star Restaurant", 3], ["4 Star Restaurant", 4], ["5 Star Restaurant", 5]] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Restauarant</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1><strong>List of all Restaurants</strong></h1>

<table>
  <thead>
    <tr>
      <th><h2><strong>Name</strong></h2></th>
      <th><h2><strong>Description</strong></h2></th>
      <th><h2><strong>Address</strong></h2></th>
      <th><h2><strong>Owner</strong></h2></th>
      <th><h2><strong>Rating</strong></h2></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><h3><%= hotel.name %></h3></td>
        <td><h3><%= hotel.description %></h3></td>
        <td><h3><%= hotel.address %></h3></td>
        <td><h3><%= hotel.owner %></h3></td>
        <td><h3><%= render_stars(hotel.rating) %></h3></td>
        <td><%= link_to 'Show / Give Review', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-7 col-md-offset-1">
<h1 class="review_title"><strong><%= @hotel.name %></strong></h1>
<h3><%= @hotel.description %></h3>
<br/> <br/>
<h2> <strong> User Reviews</strong> </h2>
<br/>
<h3> <strong>Average User Review </strong>: <%= render_stars(@avg_review) %></h3>
<br />
<% if @reviews.blank? %>
  <h3>No reviews just yet, would you like to add the first review to this restaurant!</h3>
  <%= link_to "Write Review", new_hotel_review_path(@hotel), class: "btn btn-danger" %>
<% else %>
  <% @reviews.each do |review| %>
    <div class="reviews">
      <h4><strong> User rating: </strong> <%= render_stars(review.rating) %></h4>
      <h4><%= review.comment %></h4>
      
    </div>
  <% end %>
<% end %>
</div>

<%= link_to "Write a Review", new_hotel_review_path(@hotel) %>
<br/><br/>
<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>